apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: app2-app
    newName: image-registry.openshift-image-registry.svc:5000/dev-project1/app2-app
    newTag: 1.0.0-SNAPSHOT
